### ISSUE TITLE
rake errors

### ISSUE THREAD

**Issue by vkill** [stanislaw/simple_roles#1]
# rake simple_roles_engine:install:migrations

rake aborted!
Don't know how to build task 'simple_roles_engine:install:migrations'

**Comment by stanislaw** [comment]
It is likely you're using Rails version prior to 3.1.0.

This rake task is being created by mountable engines functionality which appears only in 3.1 versions.

Let me know if you need simple_roles (read its rake tasks) working for 3.0.x versions.

**Comment by vkill** [comment]
yes, I'm going to use it for 3.0.9

**Comment by stanislaw** [comment]
I can suggest you a quick solution:

Instead of using rake task just copy files from:
https://github.com/stanislaw/simple_roles/tree/master/db/migrate 
into db/migrate folder of your project. The only thing is just changing of prefixes "001" and "002" of these files to be appropriate for your app's context.

Good luck!

**Comment by vkill** [comment]
thanks, i use #rails g migration  to migrate tables

> # rails g migration create_roles
> 
> ``` ruby
> class CreateRoles < ActiveRecord::Migration
>   def self.up
>   end
>   def self.down
>   end
>   def self.create_roles
>   end
> end
> ```
> 
> # rails g migration create_user_roles

and execute

> # rake db:migrate
> 
> it's worked
